export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const FEEDBACK_LOADING = "FEEDBACK_LOADING";
export const SUBMIT_FEEDBACK = "SUBMIT_FEEDBACK";